### PR TITLE
[enhancement] Simple changes to make site more responsive to narrow screens.

### PR DESCRIPTION
**Pull request by kwertyops**
Given the current layout of your site I think integrating a framework like Bootstrap or Tailwind is overkill, and may not even help.

There are some simple changes you can make that will help things respond better to narrower screens.

For the most part I just changed some hard-coded 'width' values to 'max-width', I changed the body vertical overflow so that it can be scrolled on a phone, and then did a little cleanup for the way that text wraps (i.e. letting the browser calculate instead of trying to hard-code break points) and tried to add some padding to let the cool background show even on small screens.

There are definitely still some issues (project images get weird on narrow screens, and the captcha will never get smaller than a certain width), but take a look and let me know what you think of these changes.

The overall design looks very cool right now so I don't want to change too much - a lot of this is creative decisions, not right/wrong, so I think those creative decisions should be up to you.

Great job! :)

### CODE REVIEW

**Comment by DylanDevelops** [comment]
@kwertyops these look good! I noticed two things that I wanted your feedback on.

1) The background seems to go and go to the right when it shouldn't. To fix this, should I just set `overflow-x: hidden;`

2) On a smaller device, the background gets created at the bottom of the viewport rather than at the bottom of the scrollable area, creating weird white space with no background. How do you suggest I fix this? If possible, I would keep it generating at the bottom of the viewport but staying frozen in that position as you scroll rather than the background scrolling with the card.

Let me know if you have any ideas for these! I appreciate your changes to the hard-set breakpoints and stuff like that! All these tips will be very helpful in the future.

**Comment by kwertyops** [comment]
@DylanDevelops 

1. Oh yeah, that's funny! - I saw the same thing and fixed it in dev tools, but never changed the code. Your fix is the same as what I did.
2. I see what you mean. It looks like 'position: fixed' instead of 'absolute' fixes it on my end.

I'll push the changes to this PR. Try out the changes and see what you think.

**Comment by DylanDevelops** [comment]
@kwertyops 

My recent commit to this branch includes changes to mobile-specific formatting for the nav buttons and project cards. I also made minor improvements, like adding more padding on the sides of the about me section to make it easier on the eyes. If you would like, take a look and send me any feedback you have. 

There are two things I noticed:

1) On mobile devices, the margin at the bottom of the footer seems to vanish and causes the footer to touch the bottom of the viewport. Why is this?

2) Unlike the projects page and homepage cards, the contact form card doesn't get smaller. Is this something you changed? If so, do you think it works as is, or should I make it so the recaptcha scales down in size to compensate for the fact that we can't change the width? Hit me with other ideas, too, if you have any!

Again, thank you so much for your continuous support in helping me clean up the code for my website! :)

**Comment by DylanDevelops** [comment]
@kwertyops 

Oh, I see. I thought there was code forcing the width to stay consistent, and I didn't realize the Recaptcha was causing it. I'll mess around with that. Thank you!

**Comment by DylanDevelops** [comment]
@kwertyops 

Okay, I found a solution. I can set the `data-size` attribute to `compact` on mobile and `normal` on regular devices, allowing the window screen to get small enough even for tiny phones. I'm working on implementing it now.

Screenshot 2023-08-01 at 2 00 21 PM

**Review by DylanDevelops — APPROVED** [review]
Everything looks good to me!

**Pull request merged**
